const api = @import("../backend.zig");
const generic = @import("generic.zig");

pub const Kind = enum { kdl, ssh_config, gitcommit, git_rebase, po, rst, latex, org, dtd, mail, hurl, ninja, rpmspec, fsharp, ocaml, gleam, commonlisp, scheme, elm, purescript, nim, d, v, odin, c3, systemverilog, llvm, openscad, nickel, hare, agda, query, vim, uxntal };

pub fn highlight(source: []const u8, sink: *api.CaptureSink, kind: Kind) api.HighlightError!void {
    try generic.highlight(source, sink, config(kind));
}

fn config(kind: Kind) generic.Config {
    return switch (kind) {
        .kdl => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .types = &.{ "i64", "f64", "string", "bool" } },
        .ssh_config => .{ .line_comments = &.{"#"}, .keywords = &.{ "Host", "Match", "HostName", "IdentityFile", "Include", "Port", "ProxyJump", "SendEnv", "SetEnv", "User" }, .case_insensitive = true },
        .gitcommit => .{ .line_comments = &.{"#"} },
        .git_rebase => .{ .line_comments = &.{"#"}, .keywords = &.{ "break", "drop", "edit", "exec", "fixup", "label", "merge", "pick", "reword", "reset", "squash", "update-ref" } },
        .po => .{ .line_comments = &.{"#"}, .keywords = &.{ "msgctxt", "msgid", "msgid_plural", "msgstr" } },
        .rst => .{ .line_comments = &.{".. "}, .keywords = &.{ "attention", "code-block", "contents", "image", "include", "note", "raw", "reference", "tip", "warning" } },
        .latex => .{ .line_comments = &.{"%"}, .keywords = &.{ "begin", "chapter", "cite", "documentclass", "emph", "end", "include", "input", "item", "label", "ref", "section", "subsection", "textbf", "usepackage" } },
        .org => .{ .line_comments = &.{"# "}, .keywords = &.{ "BEGIN_SRC", "END_SRC", "TODO", "DONE", "PROPERTIES", "END" } },
        .dtd => .{ .line_comments = &.{"<!--"}, .keywords = &.{ "ATTLIST", "DOCTYPE", "ELEMENT", "ENTITY", "NOTATION", "PUBLIC", "SYSTEM" }, .types = &.{ "ANY", "CDATA", "EMPTY", "ID", "IDREF", "NMTOKEN", "PCDATA" } },
        .mail => .{ .line_comments = &.{">"}, .keywords = &.{ "From", "To", "Cc", "Date", "Subject", "Reply-To", "Message-ID", "Content-Type" }, .case_insensitive = true },
        .hurl => .{ .line_comments = &.{"#"}, .keywords = &.{ "GET", "HEAD", "POST", "PUT", "DELETE", "OPTIONS", "PATCH", "HTTP" }, .types = &.{ "jsonpath", "regex", "xpath", "status", "url", "body", "bytes", "duration", "header" } },
        .ninja => .{ .line_comments = &.{"#"}, .keywords = &.{ "build", "default", "include", "pool", "rule", "subninja" } },
        .rpmspec => .{ .line_comments = &.{"#"}, .keywords = &.{ "Name", "Version", "Release", "Summary", "License", "Source", "BuildRequires", "Requires", "description", "prep", "build", "install", "files", "changelog" }, .case_insensitive = true },
        .fsharp => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "(*", .close = "*)" }}, .keywords = &.{ "and", "as", "class", "do", "else", "exception", "for", "fun", "function", "if", "in", "inherit", "interface", "let", "match", "member", "module", "namespace", "open", "rec", "return", "then", "try", "type", "while", "with", "yield" }, .types = &.{ "bool", "char", "float", "int", "list", "obj", "string", "unit" } },
        .ocaml => .{ .block_comments = &.{.{ .open = "(*", .close = "*)" }}, .keywords = &.{ "and", "as", "begin", "class", "do", "done", "else", "end", "exception", "for", "fun", "function", "if", "in", "include", "let", "match", "module", "of", "open", "rec", "sig", "struct", "then", "try", "type", "val", "when", "while", "with" }, .types = &.{ "bool", "bytes", "char", "float", "int", "list", "option", "string", "unit" } },
        .gleam => .{ .line_comments = &.{"//"}, .keywords = &.{ "as", "assert", "case", "const", "fn", "if", "import", "let", "opaque", "pub", "type", "use" }, .types = &.{ "BitArray", "Bool", "Float", "Int", "List", "Nil", "Result", "String" } },
        .commonlisp => .{ .line_comments = &.{";"}, .block_comments = &.{.{ .open = "#|", .close = "|#" }}, .keywords = &.{ "defclass", "defconstant", "defmacro", "defmethod", "defpackage", "defparameter", "defun", "defvar", "do", "dolist", "if", "lambda", "let", "loop", "progn", "quote", "return-from", "setq" } },
        .scheme => .{ .line_comments = &.{";"}, .block_comments = &.{.{ .open = "#|", .close = "|#" }}, .keywords = &.{ "and", "begin", "case", "cond", "define", "define-syntax", "do", "else", "if", "lambda", "let", "let*", "letrec", "or", "quote", "set!" } },
        .elm => .{ .line_comments = &.{"--"}, .block_comments = &.{.{ .open = "{-", .close = "-}" }}, .keywords = &.{ "alias", "as", "case", "else", "exposing", "if", "import", "in", "let", "module", "of", "port", "then", "type" }, .types = &.{ "Bool", "Char", "Cmd", "Float", "Int", "List", "Maybe", "Result", "String" } },
        .purescript => .{ .line_comments = &.{"--"}, .block_comments = &.{.{ .open = "{-", .close = "-}" }}, .keywords = &.{ "as", "case", "class", "data", "derive", "do", "else", "forall", "foreign", "if", "import", "in", "instance", "let", "module", "newtype", "of", "then", "type", "where" }, .types = &.{ "Array", "Boolean", "Char", "Either", "Int", "Maybe", "Number", "String", "Unit" } },
        .nim => .{ .line_comments = &.{"#"}, .block_comments = &.{.{ .open = "#[", .close = "]#" }}, .keywords = &.{ "and", "block", "break", "case", "const", "continue", "converter", "defer", "discard", "distinct", "else", "enum", "except", "for", "from", "func", "if", "import", "in", "iterator", "let", "macro", "method", "not", "object", "of", "or", "proc", "raise", "ref", "return", "template", "try", "tuple", "type", "var", "when", "while", "yield" }, .types = &.{ "bool", "byte", "char", "cstring", "float", "int", "pointer", "seq", "string", "uint", "void" } },
        .d => .{ .line_comments = &.{"//"}, .block_comments = &.{ .{ .open = "/*", .close = "*/" }, .{ .open = "/+", .close = "+/" } }, .keywords = &.{ "abstract", "alias", "align", "asm", "auto", "break", "case", "catch", "class", "const", "continue", "debug", "default", "delegate", "delete", "deprecated", "do", "else", "enum", "export", "extern", "final", "finally", "for", "foreach", "function", "goto", "if", "immutable", "import", "in", "inout", "interface", "invariant", "is", "lazy", "mixin", "module", "new", "nothrow", "out", "override", "package", "pragma", "private", "protected", "public", "pure", "ref", "return", "scope", "shared", "static", "struct", "super", "switch", "synchronized", "template", "throw", "try", "typedef", "typeid", "typeof", "union", "unittest", "version", "while", "with" }, .types = &.{ "bool", "byte", "char", "double", "float", "int", "long", "real", "short", "string", "ubyte", "uint", "ulong", "ushort", "void", "wchar" } },
        .v => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "as", "asm", "assert", "atomic", "break", "const", "continue", "defer", "else", "enum", "fn", "for", "go", "goto", "if", "import", "in", "interface", "is", "lock", "match", "module", "mut", "none", "or", "pub", "return", "rlock", "select", "shared", "sizeof", "spawn", "static", "struct", "type", "typeof", "union", "unsafe" }, .types = &.{ "bool", "byte", "char", "f32", "f64", "i16", "i32", "i64", "i8", "int", "isize", "rune", "string", "u16", "u32", "u64", "u8", "usize", "voidptr" } },
        .odin => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "asm", "auto_cast", "bit_field", "break", "case", "cast", "context", "continue", "defer", "distinct", "do", "dynamic", "else", "enum", "fallthrough", "for", "foreign", "if", "import", "in", "map", "matrix", "not_in", "or_else", "package", "proc", "return", "struct", "switch", "transmute", "typeid", "union", "using", "when", "where" }, .types = &.{ "any", "bool", "byte", "cstring", "f32", "f64", "int", "rawptr", "rune", "string", "typeid", "u16", "u32", "u64", "u8", "uint", "uintptr" } },
        .c3 => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "alias", "asm", "assert", "bitstruct", "break", "case", "catch", "const", "continue", "def", "default", "defer", "do", "else", "enum", "extern", "fault", "for", "foreach", "if", "import", "inline", "interface", "macro", "module", "nextcase", "return", "static", "struct", "switch", "try", "union", "var", "while" }, .types = &.{ "any", "bool", "char", "double", "float", "ichar", "int", "iptr", "isz", "long", "short", "string", "uint", "ulong", "uptr", "usz", "void" } },
        .systemverilog => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "always", "always_comb", "always_ff", "always_latch", "assign", "begin", "case", "class", "clocking", "covergroup", "default", "else", "end", "endcase", "endclass", "endfunction", "endmodule", "endpackage", "endtask", "enum", "for", "foreach", "function", "generate", "if", "import", "initial", "interface", "localparam", "module", "package", "parameter", "program", "property", "return", "struct", "task", "typedef", "union", "virtual", "while" }, .types = &.{ "bit", "byte", "chandle", "event", "int", "integer", "logic", "longint", "real", "realtime", "reg", "shortint", "shortreal", "signed", "string", "time", "unsigned", "wire" } },
        .llvm => .{ .line_comments = &.{";"}, .keywords = &.{ "add", "alloca", "and", "ashr", "bitcast", "br", "call", "define", "declare", "extractvalue", "fadd", "fcmp", "fdiv", "fmul", "fpext", "fptosi", "fsub", "getelementptr", "icmp", "indirectbr", "insertvalue", "invoke", "landingpad", "load", "lshr", "mul", "or", "phi", "ret", "resume", "select", "sext", "shl", "sdiv", "sitofp", "store", "sub", "switch", "trunc", "udiv", "uitofp", "unreachable", "va_arg", "xor", "zext" }, .types = &.{ "bfloat", "double", "float", "fp128", "half", "i1", "i8", "i16", "i32", "i64", "label", "metadata", "ptr", "token", "void", "x86_fp80" }, .constants = &.{ "null", "none", "poison", "undef", "zeroinitializer" } },
        .openscad => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "assert", "assign", "each", "else", "for", "function", "if", "include", "intersection_for", "let", "module", "use" }, .types = &.{ "bool", "list", "number", "range", "string", "undef" } },
        .nickel => .{ .line_comments = &.{"#"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "assume", "default", "doc", "else", "enum", "export", "forall", "force", "fun", "if", "import", "in", "let", "match", "merge", "not_exported", "optional", "or", "priority", "rec", "serialize", "then" }, .types = &.{ "Array", "Bool", "Dyn", "Enum", "Number", "Record", "String" } },
        .hare => .{ .line_comments = &.{"//"}, .block_comments = &.{.{ .open = "/*", .close = "*/" }}, .keywords = &.{ "abort", "align", "as", "assert", "break", "case", "const", "continue", "defer", "def", "else", "enum", "export", "fn", "for", "free", "if", "is", "let", "match", "nullable", "offset", "return", "static", "struct", "switch", "type", "union", "use", "vaarg", "yield" }, .types = &.{ "bool", "char", "done", "f32", "f64", "i16", "i32", "i64", "i8", "int", "never", "null", "rune", "size", "str", "u16", "u32", "u64", "u8", "uint", "uintptr", "void" } },
        .agda => .{ .line_comments = &.{"--"}, .block_comments = &.{.{ .open = "{-", .close = "-}" }}, .keywords = &.{ "abstract", "constructor", "data", "do", "eta-equality", "field", "forall", "hiding", "import", "in", "inductive", "instance", "interleaved", "irrelevant", "let", "macro", "module", "mutual", "no-eta-equality", "open", "overlap", "pattern", "postulate", "primitive", "private", "public", "quote", "record", "rewrite", "syntax", "tactic", "unquote", "unquoteDecl", "unquoteDef", "using", "variable", "where", "with" }, .types = &.{ "Level", "Prop", "Set", "Setω" } },
        .query => .{ .line_comments = &.{";"}, .keywords = &.{ "any-of", "contains", "eq", "is", "match", "not-any-of", "not-eq", "not-is", "not-match", "offset", "set" }, .constants = &.{ "ERROR", "MISSING" } },
        .vim => .{ .line_comments = &.{"\""}, .keywords = &.{ "abbreviate", "autocmd", "break", "call", "catch", "command", "continue", "def", "delcommand", "else", "elseif", "enddef", "endfor", "endfunction", "endif", "endtry", "endwhile", "execute", "finish", "for", "function", "if", "in", "let", "lockvar", "return", "set", "silent", "throw", "try", "unlet", "while" }, .types = &.{ "blob", "bool", "dict", "float", "func", "list", "number", "string" }, .constants = &.{ "null", "none", "v:null", "v:none" }, .quotes = "'" },
        .uxntal => .{ .block_comments = &.{.{ .open = "(", .close = ")" }}, .keywords = &.{ "ADD", "AND", "BRK", "DEI", "DEO", "DIV", "DUP", "EOR", "EQU", "GTH", "INC", "JCI", "JCN", "JMI", "JMP", "JSI", "JSR", "LDA", "LDZ", "LTH", "MUL", "NEQ", "NIP", "ORA", "OVR", "POP", "ROT", "SFT", "STA", "STH", "STZ", "SUB", "SWP" }, .quotes = "\"" },
    };
}
