const std = @import("std");
const syntax = @import("native_syntax");
const registry = @import("native_syntax_registry");

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len == 1) {
        var stdout_buffer: [4096]u8 = undefined;
        var stdout_writer = std.Io.File.stdout().writer(init.io, &stdout_buffer);
        try writeMatrix(&stdout_writer.interface);
        try stdout_writer.interface.flush();
        return;
    }
    if (args.len == 3 and std.mem.eql(u8, args[1], "--check")) {
        try checkMatrix(init, args[2]);
        return;
    }
    return error.InvalidArguments;
}

fn checkMatrix(init: std.process.Init, path: []const u8) !void {
    var generated: std.Io.Writer.Allocating = .init(init.gpa);
    defer generated.deinit();
    try writeMatrix(&generated.writer);

    const existing = try std.Io.Dir.cwd().readFileAlloc(
        init.io,
        path,
        init.gpa,
        .limited(std.math.maxInt(u32)),
    );
    defer init.gpa.free(existing);
    if (!std.mem.eql(u8, existing, generated.written())) {
        var stderr_buffer: [1024]u8 = undefined;
        var stderr_writer = std.Io.File.stderr().writer(init.io, &stderr_buffer);
        try stderr_writer.interface.print(
            "{s} is stale; run ./build.sh update-support-matrix\n",
            .{path},
        );
        try stderr_writer.interface.flush();
        return error.SupportMatrixOutOfDate;
    }
}

fn writeMatrix(writer: *std.Io.Writer) !void {
    if (registry.backends.len != registry.supported_backend_count) return error.IncompleteRegistry;

    var backends = registry.backends;
    std.mem.sort(syntax.Backend, &backends, {}, lessThanBackend);

    var lexical_count: usize = 0;
    var structural_count: usize = 0;
    var optional_count: usize = 0;
    for (backends) |backend| switch (backend.info.support_level) {
        .verified_lexical => {
            lexical_count += 1;
            optional_count += @intFromBool(isOptional(backend.info.canonical_name));
        },
        .verified_structural => {
            structural_count += 1;
            optional_count += @intFromBool(isOptional(backend.info.canonical_name));
        },
        .experimental => return error.ExperimentalBackend,
    };
    if (optional_count != registry.external_catalog_count) return error.IncompleteExternalMetadata;
    for (syntax.aliases) |entry| {
        const resolved = registry.backendForName(entry.alias) orelse return error.UnresolvedAlias;
        if (!std.mem.eql(u8, resolved.info.canonical_name, entry.canonical)) return error.IncorrectAlias;
    }

    try writer.print(
        \\# Supported Languages
        \\
        \\<!-- Generated by `./build.sh update-support-matrix`; do not edit manually. -->
        \\
        \\The default configured registry exposes all {d} verified backends: {d} with
        \\verified structural highlighting and {d} with verified lexical highlighting.
        \\Core backends use only Zig's standard library. Optional backends are enabled by
        \\default but can be selected with the build options shown below.
        \\
        \\| Language | Canonical name | Aliases | Implementation | Quality | Availability | Compatibility contract |
        \\| --- | --- | --- | --- | --- | --- | --- |
        \\
    , .{ backends.len, structural_count, lexical_count });

    for (backends) |backend| {
        try writer.print("| {s} | `{s}` | ", .{
            backend.info.display_name,
            backend.info.canonical_name,
        });
        try writeAliases(writer, backend.info.canonical_name);
        try writer.print(" | {s} | {s} | {s} | [{s}](compatibility/{s}.md) |\n", .{
            kindName(backend.info.kind),
            qualityName(backend.info.support_level),
            availabilityName(backend.info.canonical_name),
            contractLabel(backend.info.canonical_name),
            contractName(backend.info.canonical_name),
        });
    }

    try writer.writeAll(
        \\
        \\## Availability
        \\
        \\`core` entries are always available from the dependency-free `native_syntax`
        \\module. An `optional` entry names its `-Dbackend-*` switch and external parser
        \\package. `-Dexternal-backends=false` disables all optional entries unless an
        \\individual switch explicitly enables one. The aliases are case-insensitive and
        \\resolve only while their canonical backend is enabled.
        \\
        \\`verified lexical` means the documented token and recovery behavior has passed
        \\the shared conformance gate. `verified structural` additionally means syntax
        \\context materially affects classification. Neither level promises validation,
        \\name resolution, type checking, or complete language grammar coverage; follow the
        \\compatibility-contract link for each backend's exact boundary.
        \\
    );
}

fn lessThanBackend(_: void, left: syntax.Backend, right: syntax.Backend) bool {
    return std.mem.order(u8, left.info.canonical_name, right.info.canonical_name) == .lt;
}

fn writeAliases(writer: *std.Io.Writer, canonical_name: []const u8) !void {
    var first = true;
    for (syntax.aliases) |entry| {
        if (!std.mem.eql(u8, entry.canonical, canonical_name)) continue;
        if (!first) try writer.writeAll(", ");
        try writer.print("`{s}`", .{entry.alias});
        first = false;
    }
    if (first) try writer.writeAll("—");
}

fn kindName(kind: syntax.BackendKind) []const u8 {
    return switch (kind) {
        .lexical => "lexical",
        .parser_backed => "parser-backed",
        .composed => "composed",
    };
}

fn qualityName(level: syntax.SupportLevel) []const u8 {
    return switch (level) {
        .experimental => "experimental",
        .verified_lexical => "verified lexical",
        .verified_structural => "verified structural",
    };
}

fn availabilityName(name: []const u8) []const u8 {
    if (std.mem.eql(u8, name, "ziggy")) return "optional: `backend-ziggy` (`ziggy`)";
    if (std.mem.eql(u8, name, "ziggy-schema")) return "optional: `backend-ziggy-schema` (`ziggy`)";
    if (std.mem.eql(u8, name, "scripty")) return "optional: `backend-scripty` (`scripty`)";
    if (std.mem.eql(u8, name, "html")) return "optional: `backend-html` (`superhtml`)";
    if (std.mem.eql(u8, name, "xml")) return "optional: `backend-xml` (`superhtml`)";
    if (std.mem.eql(u8, name, "css")) return "optional: `backend-css` (`superhtml`)";
    if (std.mem.eql(u8, name, "superhtml")) return "optional: `backend-superhtml` (`superhtml`, `scripty`)";
    if (std.mem.eql(u8, name, "markdown")) return "optional: `backend-markdown` (`zig-markdown-parser`)";
    return "core";
}

fn isOptional(name: []const u8) bool {
    return !std.mem.eql(u8, availabilityName(name), "core");
}

fn contractName(name: []const u8) []const u8 {
    if (std.mem.eql(u8, name, "asm") or std.mem.eql(u8, name, "nasm")) return "assembly";
    if (std.mem.eql(u8, name, "html") or std.mem.eql(u8, name, "xml") or std.mem.eql(u8, name, "css")) return "superhtml";
    if (std.mem.eql(u8, name, "comment")) return "roadmap-84-88";
    if (std.mem.eql(u8, name, "rpmbash")) return "rpmspec";
    return name;
}

fn contractLabel(name: []const u8) []const u8 {
    if (std.mem.eql(u8, name, "asm") or std.mem.eql(u8, name, "nasm")) return "Assembly/NASM";
    if (std.mem.eql(u8, name, "html") or std.mem.eql(u8, name, "xml") or std.mem.eql(u8, name, "css")) return "SuperHTML adapters";
    if (std.mem.eql(u8, name, "comment")) return "Comment tags";
    if (std.mem.eql(u8, name, "rpmbash")) return "RPM integration";
    return name;
}
