//! Source-preserving primitives for native syntax highlighting.

const std = @import("std");

const capture = @import("capture.zig");
const backend = @import("backend.zig");

pub const html = @import("html.zig");
pub const composition = @import("composition.zig");
pub const syntax = @import("syntax.zig");
pub const Scope = @import("scope.zig").Scope;
pub const Span = capture.Span;
pub const Capture = capture.Capture;
pub const ValidationError = capture.ValidationError;
pub const Backend = backend.Backend;
pub const BackendInfo = backend.BackendInfo;
pub const BackendKind = backend.BackendKind;
pub const CaptureSink = backend.CaptureSink;
pub const HighlightError = backend.HighlightError;
pub const MetadataError = backend.MetadataError;

pub const languages = struct {
    pub const agda = @import("languages/agda.zig");
    pub const astro = @import("languages/astro.zig");
    pub const bash = @import("languages/bash.zig");
    pub const assembly = @import("languages/assembly.zig");
    pub const c = @import("languages/c.zig");
    pub const cmake = @import("languages/cmake.zig");
    pub const cpp = @import("languages/cpp.zig");
    pub const c_sharp = @import("languages/c_sharp.zig");
    pub const diff = @import("languages/diff.zig");
    pub const dockerfile = @import("languages/dockerfile.zig");
    pub const hcl = @import("languages/hcl.zig");
    pub const go = @import("languages/go.zig");
    pub const json = @import("languages/json.zig");
    pub const javascript = @import("languages/javascript.zig");
    pub const jsdoc = @import("languages/jsdoc.zig");
    pub const java = @import("languages/java.zig");
    pub const kotlin = @import("languages/kotlin.zig");
    pub const lua = @import("languages/lua.zig");
    pub const make = @import("languages/make.zig");
    pub const nasm = @import("languages/nasm.zig");
    pub const objc = @import("languages/objc.zig");
    pub const php = @import("languages/php.zig");
    pub const powershell = @import("languages/powershell.zig");
    pub const proto = @import("languages/proto.zig");
    pub const python = @import("languages/python.zig");
    pub const regex = @import("languages/regex.zig");
    pub const rust = @import("languages/rust.zig");
    pub const ruby = @import("languages/ruby.zig");
    pub const sql = @import("languages/sql.zig");
    pub const toml = @import("languages/toml.zig");
    pub const swift = @import("languages/swift.zig");
    pub const typescript = @import("languages/typescript.zig");
    pub const vue = @import("languages/vue.zig");
    pub const yaml = @import("languages/yaml.zig");
    pub const awk = @import("languages/awk.zig");
    pub const commonlisp = @import("languages/commonlisp.zig");
    pub const comment = @import("languages/comment.zig");
    pub const dtd = @import("languages/dtd.zig");
    pub const d = @import("languages/d.zig");
    pub const elixir = @import("languages/elixir.zig");
    pub const elm = @import("languages/elm.zig");
    pub const fish = @import("languages/fish.zig");
    pub const fsharp = @import("languages/fsharp.zig");
    pub const gdscript = @import("languages/gdscript.zig");
    pub const git_rebase = @import("languages/git_rebase.zig");
    pub const gitcommit = @import("languages/gitcommit.zig");
    pub const gleam = @import("languages/gleam.zig");
    pub const haskell = @import("languages/haskell.zig");
    pub const hurl = @import("languages/hurl.zig");
    pub const hare = @import("languages/hare.zig");
    pub const julia = @import("languages/julia.zig");
    pub const kdl = @import("languages/kdl.zig");
    pub const latex = @import("languages/latex.zig");
    pub const llvm = @import("languages/llvm.zig");
    pub const mail = @import("languages/mail.zig");
    pub const nim = @import("languages/nim.zig");
    pub const nickel = @import("languages/nickel.zig");
    pub const ninja = @import("languages/ninja.zig");
    pub const nix = @import("languages/nix.zig");
    pub const nu = @import("languages/nu.zig");
    pub const ocaml = @import("languages/ocaml.zig");
    pub const org = @import("languages/org.zig");
    pub const odin = @import("languages/odin.zig");
    pub const openscad = @import("languages/openscad.zig");
    pub const perl = @import("languages/perl.zig");
    pub const po = @import("languages/po.zig");
    pub const purescript = @import("languages/purescript.zig");
    pub const query = @import("languages/query.zig");
    pub const rpmbash = @import("languages/rpmbash.zig");
    pub const rpmspec = @import("languages/rpmspec.zig");
    pub const rst = @import("languages/rst.zig");
    pub const scheme = @import("languages/scheme.zig");
    pub const ssh_config = @import("languages/ssh_config.zig");
    pub const systemverilog = @import("languages/systemverilog.zig");
    pub const typst = @import("languages/typst.zig");
    pub const uxntal = @import("languages/uxntal.zig");
    pub const v = @import("languages/v.zig");
    pub const vim = @import("languages/vim.zig");
    pub const c3 = @import("languages/c3.zig");
    pub const zig = @import("languages/zig.zig");
};

test "span preserves source offsets" {
    const source = "const answer = 42;";
    const span: Span = try .init(0, 5);

    try std.testing.expectEqualStrings("const", try span.slice(source));
}
